services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/omarsaab96/orthodentlb-app
    plan: free
    region: oregon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: YOUR_DATABASE_HOST
      - key: DB_DATABASE
        value: YOUR_DATABASE_NAME
      - key: DB_USERNAME
        value: YOUR_DATABASE_USER
      - key: DB_PASSWORD
        value: YOUR_DATABASE_PASSWORD
    autoDeploy: true
